services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourSTRONG!Passw0rd"
    volumes:
      - myapp:/var/opt/mssql
volumes:
  myapp:
    external: true
